/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wrapper */

#ifndef _Included_Wrapper
#define _Included_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wrapper
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Wrapper_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
