/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sensor */

#ifndef _Included_Sensor
#define _Included_Sensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sensor
 * Method:    sense
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Sensor_sense
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
